apiVersion: v1 
kind: Service 
metadata:
  name: auth-server  
  labels:
    run: auth-server 
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    run: auth-server 
--- 
apiVersion: apps/v1beta2 
kind: Deployment 
metadata:
  name: auth-server 
spec:
  replicas: 1
  selector:
    matchLabels:
      run: auth-server
  template:
    metadata:
      labels:
        run: auth-server
    spec:
      imagePullSecrets:
      - name: {{.Values.registry}}
      containers:
      - name: auth-server
        image: 13.74.36.164:5000/vio/auth-server:0.1.2
        imagePullPolicy: Always
        env:
        - name: ARGS
          value: "-Xms32m -Xmx512m -Dspring.profiles.active=k8s-eureka,native -Dspring.cloud.config.discovery.enabled=false"
        
        
