apiVersion: v1 
kind: Service 
metadata:
  name: eureka-server
  labels:
    run: eureka-server 
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    run: eureka-server 
--- 
apiVersion: apps/v1beta2 
kind: Deployment 
metadata:
  name: eureka-server 
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eureka-server
  template:
    metadata:
      labels:
        run: eureka-server
    spec:
      imagePullSecrets:
      - name: {{.Values.registry}}
      containers:
      - name: eureka-server
        image: 13.74.36.164:5000/vio/eureka-server:0.0.1
        imagePullPolicy: Always
        env:
        - name: ARGS
          value: "-Xms32m -Xmx512m -Dspring.profiles.active=k8s-eureka,native"
        
