apiVersion: v1 
kind: Service 
metadata:
  labels:
    app: mp-cassandra
  name: mp-cassandra 
spec:
  type: NodePort
  ports:
  - port: 9042
  selector:
    app: mp-cassandra 
--- 
apiVersion: apps/v1beta2 
kind: StatefulSet 
metadata:
  name: mp-cassandra 
spec:
  serviceName: mp-cassandra
  replicas: 1
  selector:
    matchLabels:
      app: mp-cassandra
  template:
    metadata:
      labels:
        app: mp-cassandra
    spec:
      containers:
        - name: mp-cassandra
          image: cassandra:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CASSANDRA_SEEDS
              value: mp-cassandra-0.mp-cassandra.$(POD_NAMESPACE).svc.cluster.local
            - name: MAX_HEAP_SIZE
              value: 2560M
            - name: HEAP_NEWSIZE
              value: 1000M
            - name: CASSANDRA_CLUSTER_NAME
              value: "Cassandra"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
