apiVersion: v1 
kind: Service 
metadata:
  name: vio-client
  labels:
    run: vio-client 
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    run: vio-client 
--- 
apiVersion: apps/v1beta2 
kind: Deployment 
metadata:
  name: vio-client 
spec:
  replicas: 1
  selector:
    matchLabels:
      run: vio-client
  template:
    metadata:
      labels:
        run: vio-client
    spec:
      imagePullSecrets:
      - name: {{.Values.registry}}
      containers:
      - name: vio-client
        image: 13.74.36.164:5000/vio/vio-client:1.0.1
        imagePullPolicy: Always
        env:
        - name: ARGS
          value: "-Xms32m -Xmx512m"